#!/usr/bin/env bash
#
# Summary: Prints all environment variables for current working directory
#
# Usage: jlenv vars
#
# Print all jlenv-vars environment variables from `.jlenv-vars` in the
# current working directory, in the order they will be set. The output
# format is a script that may be passed to `eval` in a Bourne-
# compatible shell.
#
# For more information on jlenv-vars, see:
# https://github.com/jlenv/jlenv-vars#readme

set -e
case ${JLENV_DEBUG:-1} in
  0) # Enable tracing
    set -x
    ;;
  1) # Disable tracing
    set +x
    ;;
  *) # Disable tracing
    set +x
    ;;
esac

noop=""
verbose=""
quiet=""
# Provide jlenv completions
case "$1" in
  --complete )
    echo --help
    echo --verbose
    exit
    ;;
  -v | --verbose )
    verbose=1
    shift
    ;;
  --version )
    echo "v1.0.0"
    exit 0
    ;;
  -q | --quiet ) 
    quiet=1
    shift
    ;;
  --help )
    jlenv-help vars
    exit 0
    ;;
  -* )
    jlenv-help --usage vars >&2
    exit 1
    ;;
esac

traverse-jlenv-vars-files() {
  local root="$1"
  local results=""

  while [ -n "$root" ]; do
    if [ -e "${root}/.jlenv-vars" ]; then
      results="${root}/.jlenv-vars"$'\n'"$results"
    fi
    root="${root%/*}"
  done

  if [ -n "$results" ]; then
    echo -n "$results"
  else
    return 1
  fi
}

find-jlenv-vars-files() {
  if [ -e "${JLENV_ROOT}/vars" ]; then
    echo "${JLENV_ROOT}/vars"
  fi

  traverse-jlenv-vars-files "$JLENV_DIR" ||
  [ "$JLENV_DIR" = "$PWD" ] || traverse-jlenv-vars-files "$PWD"
}

sanitize-vars() {
  sed \
    -e "/^[ "$'\t'"]*[A-Za-z_][0-9A-Za-z_]*?\{0,1\}=/ !d" \
    -e "s/'/'\\\\''/g" \
    -e "s/\(\\\\\\\$\)/'\\1'/g" \
    -e "s/\\\\\\\\/\\\\/g" \
    -e "s/\(\\\$[0-9A-Za-z_][0-9A-Za-z_]*\)/'\\1'/g" \
    -e "s/\(\\\${[0-9A-Za-z_][0-9A-Za-z_]*}\)/'\\1'/g" \
    -e "s/^[ "$'\t'"]*\([A-Za-z_][0-9A-Za-z_]*?\{0,1\}\)=\(.*\)$/export \\1='\\2'/" \
    -e "s/export \([A-Za-z_][0-9A-Za-z_]*\)?=/[ -n \"\$\\1\" ] || export \\1=/g"
}

#####################################################################
# Main script
#####################################################################

while read file; do
  echo "# $file"
  { cat "$file"; echo; } | sanitize-vars
  echo
done < <( find-jlenv-vars-files )
